import Layout from '../Layout'
import Home from './Landing/Home'
import UserLogin from './LORE/Login/UserLogin'
import UserRegister from '../Component/LORE/Register/UserRegister'
import UserRegisterSuccess from '../Component/Success/UserRegisterSuccess'
import MainHeader from '../Component/MainPages/MainHeader'
import MainLayout from '../MainLayout'
import MainFooter from '../Component/MainPages/MainFooter.jsx'
import MainHome from '../Component/MainPages/MainHome.jsx'
import About from '../Component/Landing/About.jsx'
import Library from "../images/Library.png";
import User from "../images/user.png";
import Profile from "../images/profile.png";
import Setting from "../images/setting.png";
import Help from "../images/help.png";
import Logout from "../images/logout.png";
import Pic from "../images/pic.png";
import userLoginPNG from "../images/userLogin.jpg";
import AboutPNG from '../images/About.svg'
import Clear from '../images/Clear.png'
import SellerLogin from '../Component/LORE/Login/SellerLogin.jsx'
import SellerRegister from '../Component/LORE/Register/SellerRegister.jsx'
import SellerRegisterSuccess from '../Component/Success/SellerRegisterSuccess.jsx'
import SellerFeature from '../Component/MainPages/SellerFeatures/SellerFeature.jsx'
import Contact from '../Component/MainPages/Contact.jsx'
import MailSuccess from '../Component/Success/MailSeccess.jsx'
import Product from '../Component/ProductSection/Product.jsx'
import Search from "../images/Search.png";
import LoginPage from '../images/LoginPage.png'
import ProductDetails from '../Component/ProductSection/ProductDetails.jsx';
import sellerContact from '../images/sellerContact.svg'
import ContactSeller from '../Component/ProductSection/ContactSeller.jsx'
import DeliveryAddress from '../Component/ProductSection/DeliveryAddress.jsx'
import AddAddress from '../Component/ProductSection/AddAddress.jsx'
import PaymentGetWay from '../Component/ProductSection/PaymentGetWay.jsx'
import SettingSection from '../Component/Me/SettingSection.jsx'
import EditSection from '../Component/Me/EditSection.jsx'
// library
import LibrarianLoginImage from '../images/LibrarianLoginImage.png'
import LibraryLoginPage from '../Component/LORE/Login/LibrarianLogin.jsx'
import LibrarianRegister from '../Component/LORE/Register/LibrarianRegister.jsx'

import LibrarySection from './Maps/LibrarySection.jsx'
import LibraryPage from '../Component/Maps/LibraryPage.jsx'
import HeaderLibrary from '../Component/LibrarianLanding/HeaderLibrary.jsx'
import FooterLibrary from '../Component/LibrarianLanding/FooterLibrary.jsx'
import LibraryLayout from '../LibraryLayout.jsx'
import HomeLibrary from '../Component/LibrarianLanding/HomeLibrary.jsx'
import AddLibrary from '../Component/LibrarianLanding/AddLibrary.jsx'

export {Layout,Home,UserLogin,UserRegister,UserRegisterSuccess,MainHeader,MainLayout,MainFooter,MainHome,About,Library,User,LibrarianLoginImage,Profile,Setting,Help,Logout,Pic,userLoginPNG,AboutPNG,Clear,Search,SellerLogin,SellerRegister,SellerRegisterSuccess,SellerFeature,Contact,MailSuccess,Product,LoginPage,ProductDetails,sellerContact,ContactSeller,DeliveryAddress,AddAddress,PaymentGetWay,SettingSection,EditSection,LibraryLoginPage,LibrarySection,LibraryPage,LibrarianRegister,HeaderLibrary,FooterLibrary,LibraryLayout,HomeLibrary,AddLibrary};